config/routes.rb
Rails.application.routes.draw do
  root 'boards#index'
  resources :boards do
  	resources :lists
  end
end

app/models/board.rb
class Board < ActiveRecord::Base
	validates_presence_of :name
	has_many :lists
end

app/models/list.rb
class List < ActiveRecord::Base
	validates_presence_of :name
	belongs_to :board
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  def index
  	@boards = Board.all
  end

  def create
  	@board = Board.create(board_params)
  	if @board.save
  		render json: @board
  	else
  		render json: {errors: @board.errors.full_messages }
  	end
  end

  def destroy
    @board =Board.find(params[:id])
    @board.destroy
    render json: {message: 'Board Deleted'}
  end

  private

  	def board_params
  		params.require(:board).permit(:name, :description)
  	end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :find_board

  def index
    render json: @board.lists
  end

  def create
    @list = @board.lists.new(list_params)
    if @list.save
      render json: @list
    else
      render json: {errors: @list.errors.full_messages}
    end
  end

  def destroy
    @board.lists.find(params[:id]).destroy
    render json: {message: 'list deleted'}
  end

  private
    def find_board
      @board = Board.find(params[:board_id])
    end

    def list_params
      params.require(:list).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/boards/index.html.haml
%h1.center Trello React Boards
%hr
-# .container.black.white-text
-# 	some text

-# 	%ul
-# 		- [1,2,3,4,5].each do |number|
-# 			%li
-# 				= number
-# #content.pink.whit-text.center
-# 	%h3 Some content
-# 	%img.circle{src: 'https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTdsD6tg7yEzZggd6b73ODlbw6iUPyzMQ7g28ADMZlAMQP05lRH'}
-# 	%a#some-id.app-link{href: '/boards', class: 'app-link', data: {confirm: 'really go to board?' } }
-# 	%hr
-# 	= link_to 'Boards', boards_path, data: {confirm: 'Really go to boards?'}

-# 	= form_for Board.new do |f|
-# 		= f.label :name
-# 		= f.text_field :name

-# 		= f.label :description
-# 		= f.text_field :description

-# - if @boards.any?
-# 	- @boards.each do |board|
-# 		- link_to board.name, board_path(board)

-# - else 
-# 	%h3 No boards, please create one!

-# = link_to 'New Board', new_board_path

= react_component('Boards', {boards: @boards})

app/views/layouts/application.html.haml
!!!
%html
	%head
		%title Trello Clone React
		= stylesheet_link_tag 'application', media: 'all'
		= javascript_include_tag 'application'
		= csrf_meta_tags
	%body
		= yield

app/views/lists/index.html.haml
%h1 Lists#index
%p Find me in app/views/lists/index.html.haml